name: First Workflow
on: workflow_dispatch

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run Hello World
        run: echo "Hello World!"
      - name: Run Complete step
        run: echo "Done - Thank you!"
